# Generated by Django 4.2.7 on 2024-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
