# Generated by Django 4.2.7 on 2024-05-01 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_modify_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 6, 0, 59, 274129)),
        ),
    ]
