# Generated by Django 4.2.7 on 2024-05-03 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_notes_alter_ticket_ticket_modify_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_modify_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 23, 45, 55, 798049)),
        ),
    ]
