# Generated by Django 4.2.7 on 2024-05-03 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_ticket_modify_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_modify_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 0, 56, 54, 669644)),
        ),
    ]
