# Generated by Django 4.2.7 on 2024-05-03 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_note_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='last_modified_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_modify_time',
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 3, 22, 13, 288208)),
        ),
    ]
