# Generated by Django 4.2.7 on 2024-05-03 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_ticket_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 4, 3, 45, 52, 626675)),
        ),
    ]
